By default do not test on 3.12. (#230)
Packages that use gocept.pytestlayer are broken then, because it is not compatible.
It is being replaced by zope.pytestlayer.
Sample error:
https://github.com/plone/plone.releaser/actions/runs/9086068912/job/24970903122
ModuleNotFoundError: No module named 'imp'